version: '3.9'

services:

  voucher-pool:
    build: .
    network_mode: host
    restart: always
    env_file : 
      - ./env/dev.env
  postgres:
    image: postgres:14-alpine
    ports:
      - 5434:5432
    volumes:
      - ./apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=user
      - POSTGRES_DB=voucherdb
    networks:
        - rabbitmq_go_net
    restart: always

  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    networks:
      - rabbitmq_go_net
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    # volumes:
    #   - "./prometheus-grafana.yml:/etc/grafana/provisioning/datasources
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge