global:
  scrape_interval: 15s

scrape_configs:
   - job_name: voucher-app
     metrics_path: /voucher/metrics
     static_configs:
      - targets:
          - 'prometheus:9090'
          - 'host.docker.internal:3001'